web/router.ex
defmodule BlogSystrix.Router do
  use BlogSystrix.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BlogSystrix do
    pipe_through :browser # Use the default browser stack

    get "/", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
    resources "/posts", PostController do
      post "/comment", PostController, :add_comment
    end
    resources "/users", UserController
    get "/registration", RegistrationController, :new
    post "/registration", RegistrationController, :create
    
    get "/pages", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", BlogSystrix do
  #   pipe_through :api
  # end
end

web/models/post.ex
defmodule BlogSystrix.Post do
  use BlogSystrix.Web, :model

  schema "posts" do
    field :title, :string
    field :body, :string
    belongs_to :user, BlogSystrix.User, foreign_key: :user_id
    has_many :comments, BlogSystrix.Comment, on_delete: :fetch_and_delete

    timestamps
  end

  @required_fields ~w(title body user_id)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end

  def count_comments(post) do
    from p in post,
      group_by: p.id,
      left_join: c in assoc(p, :comments),
      select: {p, count(c.id)}
  end


end

web/controllers/post_controller.ex
defmodule BlogSystrix.PostController do
  use BlogSystrix.Web, :controller
  
  alias BlogSystrix.User
  alias BlogSystrix.Post
  alias BlogSystrix.Comment
  plug BlogSystrix.Plug.Authenticate
  plug :scrub_params, "post" when action in [:create, :update]
  plug :scrub_params, "comment" when action in [:add_comment]


  def index(conn, _params) do
    current_user_id = Plug.Conn.get_session(conn, :current_user).id
    query = from p in Post, where: p.user_id == ^current_user_id
    query = Post.count_comments(query) 
    posts_user = Repo.all(query)
    query2 = from p in Post, where: p.user_id != ^current_user_id
    query2 = Post.count_comments(query2) 
    other_posts = Repo.all(query2)
    conn
    |> put_layout("logged_in.html")
    |> render("index.html", posts_user: posts_user, other_posts: other_posts)
  end

  def new(conn, _params) do
    changeset = Post.changeset(%Post{})
    conn
    |> put_layout("logged_in.html")
    |> render("new.html", changeset: changeset)
  end

  def create(conn, %{"post" => post_params}) do
    current_user_id = Plug.Conn.get_session(conn, :current_user).id
    changeset = Post.changeset(%Post{}, Map.put(post_params, "user_id", current_user_id))
    case Repo.insert(changeset) do
      {:ok, _post} ->
        conn
        |> put_layout("logged_in.html")
        |> put_flash(:info, "Post creado satisfactoriamente.")
        |> redirect(to: post_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def add_comment(conn, %{"comment" => comment_params, "post_id" => post_id}) do
    current_user_id = Plug.Conn.get_session(conn, :current_user).id
    comment_params = Map.put(comment_params, "post_id", post_id)
    comment_params = Map.put(comment_params, "user_id", current_user_id)
    changeset = Comment.changeset(%Comment{}, comment_params)
    post = Post |> Repo.get(post_id) |> Repo.preload([:comments])
    case Repo.insert(changeset) do
      {:ok, comment} ->
        conn
        |> put_layout("logged_in.html")
        |> put_flash(:info, "El comentario ha sido agregado correctamente.")
        |> redirect(to: post_path(conn, :show, post))
      {:error, changeset} ->
        render(conn, "show.html", post: post, changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    #post = Repo.get!(Post, id) |> Repo.preload([:comments])
    post = Repo.get!(Post, id) |> Repo.preload([comments: :user])
    IO.inspect "--- Imprimiendo por consola lo que genera el query ---"
    IO.inspect post
    changeset = Comment.changeset(%Comment{})
    conn
    |> put_layout("logged_in.html")
    |> render("show.html", post: post, changeset: changeset)
  end

  def edit(conn, %{"id" => id}) do
    post = Repo.get!(Post, id)
    changeset = Post.changeset(post)
    conn
    |>  put_layout("logged_in.html")
    render(conn, "edit.html", post: post, changeset: changeset)
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Repo.get!(Post, id)
    changeset = Post.changeset(post, post_params)

    case Repo.update(changeset) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post actualizado satisfactoriamente.")
        |> redirect(to: post_path(conn, :show, post))
      {:error, changeset} ->
        render(conn, "edit.html", post: post, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    post = Repo.get!(Post, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(post)

    conn
    |> put_flash(:info, "Post borrado satisfactoriamente.")
    |> redirect(to: post_path(conn, :index))
  end
end

web/views/post_view.ex
defmodule BlogSystrix.PostView do
  use BlogSystrix.Web, :view
end

web/templates/post/comment_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :content, "Comentario", class: "control-label" %>
    <%= textarea f, :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Agregar Comentario", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/post/comments.html.eex
<h3>Comments: </h3>
<table class="table">
	<thead>
		<tr>
			<th>Usuario</th>
			<th>Comentario</th>
		</tr>
	</thead>
	<tbody>
		<%= for comment <- @post.comments do %>

			<tr>
				<td><%= comment.user.nombre %></td>
				<td><%= comment.content %></td>
			</tr>
		<% end %>
	</tbody>
</table>

web/templates/post/edit.html.eex
<h2>Edit post</h2>

<%= render "form.html", changeset: @changeset,
                        action: post_path(@conn, :update, @post) %>

<%= link "Back", to: post_path(@conn, :index) %>

web/templates/post/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, "Titulo", class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :body, "Contenido", class: "control-label" %>
    <%= textarea f, :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/post/index.html.eex
<h2>Mis Posts</h2>
<%= link "New post", to: post_path(@conn, :new), class: "btn btn-primary btn-xs" %>
<table class="table">
  <thead>
    <tr>
      <th>Título</th>
      <th>Total Comentarios</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for {post, count} <- @posts_user do %>
    <tr>
      <td><%= post.title %></td>
      <td><%= count %></td>

      <td class="text-right">
        <%= link "Ver mas", to: post_path(@conn, :show, post), class: "btn btn-default btn-xs" %>
        <%= link "Editar", to: post_path(@conn, :edit, post), class: "btn btn-default btn-xs" %>
        <%= link "Borrar", to: post_path(@conn, :delete, post), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<h2>Otros Posts</h2>
<table class="table">
  <thead>
    <tr>
      <th>Título</th>
      <th>Total Comentarios</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for {post, count} <- @other_posts do %>
    <tr>
      <td><%= post.title %></td>
      <td><%= count %></td>

      <td class="text-right">
        <%= link "Ver mas", to: post_path(@conn, :show, post), class: "btn btn-default btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

web/templates/post/new.html.eex
<h2>New post</h2>

<%= render "form.html", changeset: @changeset,
                        action: post_path(@conn, :create) %>

<%= link "Back", to: post_path(@conn, :index) %>

web/templates/post/show.html.eex
<h2>Show post</h2>

<ul>

  <li>
    <strong>Titulo:</strong>
    <%= @post.title %>
  </li>

  <li>
    <strong>Contenido:</strong>
    <%= @post.body %>
  </li>

</ul>

<%= link "Edit", to: post_path(@conn, :edit, @post) %>
<%= link "Back", to: post_path(@conn, :index) %>

<%= render "comment_form.html", post: @post, changeset: @changeset, action: post_post_path(@conn, :add_comment, @post) %>
<%= render "comments.html", post: @post %>