web/router.ex
defmodule BlogSystrix.Router do
  use BlogSystrix.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BlogSystrix do
    pipe_through :browser # Use the default browser stack

    get "/", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
    resources "/posts", PostController do
      post "/comment", PostController, :add_comment
    end
    resources "/users", UserController
    get "/registration", RegistrationController, :new
    post "/registration", RegistrationController, :create
    
    get "/pages", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", BlogSystrix do
  #   pipe_through :api
  # end
end

web/controllers/session_controller.ex
defmodule BlogSystrix.SessionController do
  use BlogSystrix.Web, :controller

  alias BlogSystrix.User

  plug :scrub_params, "user" when action in [:create]

  def new(conn, _params) do
    render conn, changeset: User.changeset(%User{})
  end

  def create(conn, %{"user" => user_params}) do
    user = if is_nil(user_params["email"]) do
      nil
    else
      Repo.get_by(User, email: user_params["email"])
    end

    user
      |> sign_in(user_params["password"], conn)
  end

  def delete(conn, _) do
    delete_session(conn, :current_user)
      |> put_flash(:info, 'Se ha deslogueado')
      |> redirect(to: session_path(conn, :new))
  end

  defp sign_in(user, password, conn) when is_nil(user) do
    conn
      |> put_flash(:error, 'Usuario no registrado.')
      |> render "new.html", changeset: User.changeset(%User{})
  end

  defp sign_in(user, password, conn) when is_map(user) do
    cond do
      Comeonin.Bcrypt.checkpw(password, user.encrypted_password) ->
        conn
          |> put_session(:current_user, user)
          |> put_layout("logged_in.html")
          |> put_flash(:info, 'Se ha logueado.')
          |> redirect(to: post_path(conn, :index))
      true ->
        conn
          |> put_flash(:error, 'Email o password incorrectos.')
          |> render "new.html", changeset: User.changeset(%User{})
    end
  end
end

web/views/session_view.ex
defmodule BlogSystrix.SessionView do
  use BlogSystrix.Web, :view
end

web/templates/session/new.html.eex
<h3>Login</h3>
<%= form_for @changeset, session_path(@conn, :create), fn f -> %>
  <%= if f.errors != [] do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :email, "Email", class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :password, "Password", class: "control-label" %>
    <%= password_input f, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Login", class: "btn btn-primary" %>
    <%= link("Sign Up", to: registration_path(@conn, :new), class: "btn btn-success pull-right") %>
  </div>
<% end %>